### ISSUE TITLE
Khino's Soundtrack Expansion mod fails to download and integrate.

### ISSUE THREAD

**Issue by Radial36** [trumank/drg-mod-integration#109]
When attempting to install mods while this mod is enabled, it ends up failing. I haven't caught at which percentage exactly it fails, but when it does i get [this error](https://pastebin.com/Fd0CX50g) in the log file.

Downloading the mod off mod.io manually and installing locally is not an option, as manual downloads are disabled by the creator.

**Comment by trumank** [comment]
```
            source: hyper::Error(
                Connect,
                ConnectError(
                    "dns error",
                    Os {
                        code: 11001,
                        kind: Uncategorized,
                        message: "No such host is known.",
                    },
                ),
            ),
```
This says it's a DNS issue resulting from the `api.mod.io` domain. This indicates either a temporary networking issue or the domain is blocked on your network in some capacity, and is not an issue with the integrator itself. I have also verified I can install the mod just fine on my system.
