### ISSUE TITLE
FIXED! - New update - keeps crashing when launching game?

### ISSUE THREAD

**Issue by Plagueinjector** [trumank/drg-mod-integration#111]
Hello

After game update, the game keeps crashing when launching.

Error message:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000223cce5ffd0

FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
kernel32
ntdll

**Comment by Plagueinjector** [comment]
Okay i fixed it. 

Apparently they changed the path to the DRG FSD-WindowsNoEditor.pak

I found it under D:\Steam\steamapps\common\Deep Rock Galactic\FSD\Content\Paks

Just redo the path correctly and it will work again.

**Comment by trumank** [comment]
Was re-opening intentional?
