### ISSUE TITLE
Install mods failed with "An existing connection was forcibly closed by the remote host" (OS error 10054)

### ISSUE THREAD

**Issue by Stethor** [trumank/drg-mod-integration#112]
System: Windows 10 Pro 22H2
Log:
ERROR drg_mod_integration::gui::message: modio::Error {
    kind: Request,
    source: Reqwest(
        reqwest::Error {
            kind: Request,
            url: Url {
                scheme: "https",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: Some(
                    Domain(
                        "api.mod.io",
                    ),
                ),
                port: None,
                path: "/v1/games/2475/mods/3500942/files/4517798/download/7ba01aef6b12feb32ce6dc92f008d945",
                query: None,
                fragment: None,
            },
            source: hyper::Error(
                Io,
                Os {
                    code: 10054,
                    kind: ConnectionReset,
                    message: "An existing connection was forcibly closed by the remote host.",
                },
            ),
        },
    ),
}
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: BaseThreadInitThunk
  21: RtlUserThreadStart

**Comment by trumank** [comment]
Can you open the URL presented in the log in a web browser? It should download the mod file. If it doesn't then your system can't access mod.io for some reason: https://api.mod.io/v1/games/2475/mods/3500942/files/4517798/download/7ba01aef6b12feb32ce6dc92f008d945

**Comment by Stethor** [comment]
Uhh, despite having this issue for entire day, right know it fixed itself.. somehow. I was trying to get the error again to get acsess to the fresh download link, but instead everything works now. I might re-open the issue if i encounter this problem again and will provide the error message from browser.

**Comment by SplitSentro** [comment]
Had the same issue after updating cache for multiple dozens of mods in a profile for about 10 minutes. Feels like mod.io just timeouts ip after some intensive querying from Mod Integration. Replacing token doesn't help with it. It randomly starts working later.

**Comment by trumank** [comment]
Ah I think I have run into that before, but I haven't seen it implemented request backoffs. Maybe it can still be rarely triggered from multiple parallel requests hitting the rate limit at just the wrong time? Could try reducing the number of parallel requests slightly, but hard to test if it happens so rarely.

**Comment by fgdhyt124** [comment]
This problem started recently and has already pissed me off. Because of this error I am now sitting without mods. The funny thing is that indeed, the error sometimes resolves itself, but this is only with the addition of mods, but as soon as it comes to install or update the cache, but all, dead. http request error, connection error and so on. And it's not even with any particular mods and their number happens, but in general the problem has grown to the most uncomfortable stage. I hope the solution to the problem will not wait long
![Безымянный](https://github.com/trumank/drg-mod-integration/assets/61048581/0bfe64fe-ed05-46bd-9ccb-dbec9c7a8fdc)

**Comment by SCHENEV-gh** [comment]
Hahaha, love the irony. All I had to do was whine and try it after a while and it worked like nothing happened. So if it doesn't work, you have to try again after a while? Well, God bless you
