### ISSUE TITLE
Praetorian Gas Visual Bug

### ISSUE THREAD

**Issue by snickas** [trumank/drg-mod-integration#21]
Only the black particles from the gas appear visible causing praetorian gas to be very difficult to see. 

![20230801230632_1](https://github.com/trumank/drg-mod-integration/assets/85909569/1bd49b5d-324e-4f31-9bc2-c7695c9356ac)

![20230801230415_1](https://github.com/trumank/drg-mod-integration/assets/85909569/0e0b1206-f7e6-4ed4-8aec-b39b0ff09a7a)

**Comment by trumank** [comment]
Mod list?

**Comment by snickas** [comment]
https://mod.io/g/drg/m/shout-framework#2751974
https://mod.io/g/drg/m/siirvend-mission-control#1151344
https://mod.io/g/drg/m/only-bugs-no-content#2959011
https://mod.io/g/drg/m/streamsuit-5000-tools#2155079
https://mod.io/g/drg/m/more-fov#1150682
https://mod.io/g/drg/m/promotion-levels-after-legendary-3-indicator#2369777
https://mod.io/g/drg/m/improved-fire-bomber-projectile-visibility#3187876
https://mod.io/g/drg/m/motd-stattrack#1145532
https://mod.io/g/drg/m/purple-flamethrower#3179565
https://mod.io/g/drg/m/hotkeys#2498386
https://mod.io/g/drg/m/better-unknown-horror-indicator#2503544
https://mod.io/g/drg/m/combined-presets#2814623
https://mod.io/g/drg/m/revert-resupply-stacking#2909497
https://mod.io/g/drg/m/revert-preatorian-gas-bug-mostly#2942827
https://mod.io/g/drg/m/modified-gunner-shield-effect#3029397
https://mod.io/g/drg/m/death-marker#3035859
https://mod.io/g/drg/m/deep-dive-secondaries-on-normal-missions-season4#3122386
https://mod.io/g/drg/m/no-ragdolls#2121639
https://mod.io/g/drg/m/sprint-by-default-hold-to-walk#2152235
https://mod.io/g/drg/m/fix-grenade-collision#2190584
https://mod.io/g/drg/m/revert-em-discharge#2191437
https://mod.io/g/drg/m/customizable-weapon-fov#2334132
https://mod.io/g/drg/m/actual-sound-for-cave-leech-movement-season-2#2348581
https://mod.io/g/drg/m/goldchunksbegone#2424882
https://mod.io/g/drg/m/clutterbegone#2434441
https://mod.io/g/drg/m/customizable#2478655
https://mod.io/g/drg/m/combined-resources#1863656
https://mod.io/g/drg/m/better-spectator-reloaded#1877135
https://mod.io/g/drg/m/azusas-weapon-sound-pack#1888355
https://mod.io/g/drg/m/simpleqol#1956173
https://mod.io/g/drg/m/ironwill-count-down-voice#1960533
https://mod.io/g/drg/m/buyable-missions#1962912
https://mod.io/g/drg/m/miracle-mod-manager#1582325
https://mod.io/g/drg/m/advanced-darkness-reloaded#2029130
https://mod.io/g/drg/m/refined-assignments#2041465
https://mod.io/g/drg/m/build-inspector#2101319
https://mod.io/g/drg/m/googly#2101850
https://mod.io/g/drg/m/vaporwave-legendary-borders#1616717
https://mod.io/g/drg/m/sticky-flame-status-icons#1618289
https://mod.io/g/drg/m/weapon-heat-crosshair#1634437
https://mod.io/g/drg/m/live-mission-stat-tracker#1636619
https://mod.io/g/drg/m/platform-placement-preview#1674997
https://mod.io/g/drg/m/no-mission-control-ducking#1751367
https://mod.io/g/drg/m/stock-and-bosco-weapon-paintjob-unlocker#1807375
https://mod.io/g/drg/m/lbs-base-kit#2986917
https://mod.io/g/drg/m/custom-vanity-framework#2432311
https://mod.io/g/drg/m/better-explosion-range-indicator#1831206
https://mod.io/g/drg/m/custom-difficulty#1861561
https://mod.io/g/drg/m/customizable-ally-outlines#1533299
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/all-deep-dives-hazard-5#1519511
https://mod.io/g/drg/m/disruptive-audio-removal-pack-plus#1372030
https://mod.io/g/drg/m/classes-icon-mammal-theme#1160676
https://mod.io/g/drg/m/no-camera-shake#1158572
https://mod.io/g/drg/m/cosmetic-restriction-remover#1158356
https://mod.io/g/drg/m/remove-flares#1123715
https://mod.io/g/drg/m/remove-all-particles#1034587
https://mod.io/g/drg/m/drglib#1034237

**Comment by jieyouxu** [comment]
Reduced to Clutter Be Gone!

MCVE mod list (incl. debug helper mods):

```
https://mod.io/g/drg/m/sandbox-utilities#1897251
https://mod.io/g/drg/m/clutterbegone#2434441
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/drglib#1034237
```

**Comment by trumank** [comment]
Caused by `FSD/Content/Art/Textures/Smoke/T_SmokeSubUV01` in Clutter Be Gone, similar to #22:

The mod includes these broken assets, but because the official integration doesn't load them, the issues never appears. I don't see a great way to solve this without patching the mods themselves because the integration tool is behaving correctly.
