### ISSUE TITLE
Local mod not loading bp mod from mod.io

### ISSUE THREAD

**Issue by Lesgo18** [trumank/drg-mod-integration#36]
In v0.2.8 when you use local mod it stop bp mod from working. When local mod is disable it is working again. Older version works fine

**Comment by jieyouxu** [comment]
Gonna need some more information on this:

1. Which local mod? Can you send the `.pak` file?
2. Can you post your complete mod list which can reproduce this issue?

**Comment by Lesgo18** [comment]
> Gonna need some more information on this:
> 
> 1. Which local mod? Can you send the `.pak` file?
> 2. Can you post your complete mod list which can reproduce this issue?

Not on my computer rn ill post it later

**Comment by Lesgo18** [comment]
my local mod: [x_modded.zip](https://github.com/trumank/drg-mod-integration/files/12269265/x_modded.zip)

mod list:
C:\CustomProgram\DRGPacker4.27\x_modded.pak
https://mod.io/g/drg/m/remove-mineral-scatter#1365047
https://mod.io/g/drg/m/remove-rockpox-particles#3205713
https://mod.io/g/drg/m/xmas-zips#1606854
https://mod.io/g/drg/m/rock-and-stonepilled-season-2-update#2180950
https://mod.io/g/drg/m/better-unknown-horror-indicator#2503544
https://mod.io/g/drg/m/better-contrasting-twins-recolored-arbalest#2525496
https://mod.io/g/drg/m/stockingbucket#1637267
https://mod.io/g/drg/m/yuletide#2566820
https://mod.io/g/drg/m/better-beers-extra-strength-underhills#2032299
https://mod.io/g/drg/m/ammo-percentage-indicator#2613099
https://mod.io/g/drg/m/more-hp-bars#3148183
https://mod.io/g/drg/m/pingtotext#2273035
https://mod.io/g/drg/m/motd-stattrack#1145532
https://mod.io/g/drg/m/better-post-processing-reloaded#2025849
https://mod.io/g/drg/m/karl-comeback-last-dwarf-standing#2990379
https://mod.io/g/drg/m/better-cracking-boots#3096163
https://mod.io/g/drg/m/no-web-no-problem#2939176
https://mod.io/g/drg/m/sandbox-utilities#1897251
https://mod.io/g/drg/m/spawn-menu#1157000
https://mod.io/g/drg/m/craft-beer-effect-menu#2685922
https://mod.io/g/drg/m/aichis-beer-selector#2965513
https://mod.io/g/drg/m/host-only-buttons#2750508
https://mod.io/g/drg/m/revert-resupply-stacking#2909497
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/drglib#1034237
https://mod.io/g/drg/m/sgg-framework-files#3096846
https://mod.io/g/drg/m/more-arcades#3094888
https://mod.io/g/drg/m/starship-troopers-music-rep-klendathu-fever#1169791
https://mod.io/g/drg/m/lodsofemone-jukebox-replacer#2071320
https://mod.io/g/drg/m/fix-centered-names#2191191
https://mod.io/g/drg/m/airmolly#2038940
https://mod.io/g/drg/m/vaporwave-promotion-borders-full-set#1620474
https://mod.io/g/drg/m/sticky-flame-status-icons#1618289
https://mod.io/g/drg/m/white-throwing-flares#1034748
https://mod.io/g/drg/m/vine-boom-for-laser-pointer#2728755
https://mod.io/g/drg/m/unique-status-effect-icons-hud-elements#1250251
https://mod.io/g/drg/m/seasonal-space-rig#1160469
https://mod.io/g/drg/m/let-there-be-light#1034830
https://mod.io/g/drg/m/weapons-in-space-rig#1533287
https://mod.io/g/drg/m/dynamic-nitra-cost#1490893/3341725
https://mod.io/g/drg/m/speedster#1139370
https://mod.io/g/drg/m/brighter-objects-add-on#1720132
https://mod.io/g/drg/m/more-players-balanced#2515857
https://mod.io/g/drg/m/goldchunksbegone#2424882
https://mod.io/g/drg/m/ashless-radioactive-exclusion-zone#1034161
https://mod.io/g/drg/m/advanced-darkness-reloaded#2029130
https://mod.io/g/drg/m/simpleqol#1956173
https://mod.io/g/drg/m/platform-effect-indicator#1824234
https://mod.io/g/drg/m/glowing-equipment#1751567
https://mod.io/g/drg/m/better-bolt-indicator#2100272
https://mod.io/g/drg/m/clutterbegone#2434441
https://mod.io/g/drg/m/alternate-player-list-ui#2553961
https://mod.io/g/drg/m/death-marker#3035859
https://mod.io/g/drg/m/closer-promotion-terminal-updated#2092879
https://mod.io/g/drg/m/promotion-levels-after-legendary-3-indicator#2369777
https://mod.io/g/drg/m/no-ragdolls#2121639
https://mod.io/g/drg/m/better-spectator-reloaded#1877135
https://mod.io/g/drg/m/customizable-ally-outlines#1533299
https://mod.io/g/drg/m/ayo-the-resupply-here#1521216
https://mod.io/g/drg/m/rancors-rig-hud#1769472
https://mod.io/g/drg/m/remove-all-particles-but-weaponsntools#1034644
https://mod.io/g/drg/m/better-explosion-range-indicator#1831206
https://mod.io/g/drg/m/cosmetic-restriction-remover#1158356
https://mod.io/g/drg/m/platform-placement-preview#1674997
https://mod.io/g/drg/m/combined-resources#1863656

**Comment by jieyouxu** [comment]
Thanks!

**Comment by trumank** [comment]
This seems to be caused by the recent case insensitivity changes. Unreal Engine seems to load most assets case insensitively, but looks like mismatched case breaks inheritance (game mode subclasses in this case e.g. `GM_EggCollection`). I think the proper solution is tweaking the `repak` crate to properly handle case insensitive directories.
