### ISSUE TITLE
Touhou OST to DRG mod sometimes not working properly with mod integration but works fine on mod.io

### ISSUE THREAD

**Issue by jieyouxu** [trumank/drg-mod-integration#47]
Mod link: https://mod.io/g/drg/m/touhou-ost-to-drg

> songs often dont play on the space rig and on missions like refinery songs tend to stack on top of each other

User reports mod works fine on mod.io, but needs additional confirmation and testing.

**Comment by trumank** [comment]
Are there any accompanying mods that may be causing conflicts? It looks to be a fairly simple audio asset replacement mod so I don't see how it could behavior could be subtle broken compared to the official integration.

**Comment by jieyouxu** [comment]
> alright its the mod itself thats borked actually, it doesnt work on mod.io either even when its the only one enabled
