### ISSUE TITLE
Re-Forged causes other mods to not open

### ISSUE THREAD

**Issue by MichaelsDRGMods** [trumank/drg-mod-integration#49]
When [DRG Re-Forged](https://mod.io/g/drg/m/deep-rock-galactic-re-forged-2-beta#2060737) is added to the game, all other mods seem to not work (can't open mod-hub, etc). It works properly in DRG's modloader. This could be a copy of #33 but I'm not sure how Re-forged was compressed.

**Comment by trumank** [comment]
Almost certainly related to #36 which is fixed pending next release. I'll see if I can cut a new release today.

**Comment by trumank** [comment]
Fixed in latest release
