### ISSUE TITLE
Improve error message when user tries to add mod through preview URL

### ISSUE THREAD

**Issue by Buckminsterfullerene02** [trumank/drg-mod-integration#51]
Example URL: https://mod.io/g/drg/m/bucks-shitty-audio-modpack?preview=b2af1287d7ec5cae8d7a2994717b639b

The following error occurs when adding the mod:
```
modio::Error {
    kind: Validation(
        "Validation Failed. Please see below to fix invalid input:",
        {
            "name_id": "The \"name id\" may not be greater than 50 characters.",
        },
    ),
}
```

@jieyouxu can you see if you can replicate? it works for truman, but it could be because his account automatically has access to everything due to being a community moderator.

**Comment by jieyouxu** [comment]
@Buckminsterfullerene02 I can indeed reproduce this issue.

**Comment by trumank** [comment]
That URL will definitely not work currently since it doesn't match the regex for mod.io URLs. You might be able to subscribe to it in a web browser first and then paste the URL without the preview token.

**Comment by jieyouxu** [comment]
> That URL will definitely not work currently since it doesn't match the regex for mod.io URLs. You might be able to subscribe to it in a web browser first and then paste the URL without the preview token.

We should probably improve the error message for this then, as it doesn't explain actual issue I think, now that we have logging infrastructure setup.

**Comment by jieyouxu** [comment]
> That URL will definitely not work currently since it doesn't match the regex for mod.io URLs. You might be able to subscribe to it in a web browser first and then paste the URL without the preview token.

We should probably improve the error message for this then, as it doesn't explain actual issue I think, now that we have logging infrastructure setup.

**Comment by Buckminsterfullerene02** [comment]
I misunderstood how the preview link system worked. @jieyouxu maybe just to double check, try subscribing to the mod via the preview link and then seeing if adding the mod via the normal mod URL works for you.

**Comment by jieyouxu** [comment]
> I misunderstood how the preview link system worked. @jieyouxu maybe just to double check, try subscribing to the mod via the preview link and then seeing if adding the mod via the normal mod URL works for you.

Yes, that does work for me once I subscribed to it.

**Comment by Buckminsterfullerene02** [comment]
Okay cool, then this is not a bug, but I could leave this open as an issue to improve error messages for user error with preview URLs?
