### ISSUE TITLE
UWP version lacks save game functionality

### ISSUE THREAD

**Issue by trumank** [trumank/drg-mod-integration#58]
The MS store version of the game has limited save game support so all mods using custom save games end up overwriting the *player's save file*. The save functions should be hooked to restore ability to write to save files with a custom path.

**Comment by Buckminsterfullerene02** [comment]
The PLAYER'S save?!!?! 💀

**Comment by trumank** [comment]
Yes, though most of the time it ends up working out since the save will be loaded before mod actors are spawned and then saved again after mod actors have been destroyed. I imagine things become an issue if the game crashes somewhere in the middle.
