### ISSUE TITLE
Mods dont work. 

### ISSUE THREAD

**Issue by yomanoel** [trumank/drg-mod-integration#8]
CMD shows an error message saying "The system couldnt find the specified file."

![image](https://github.com/trumank/drg-mod-integration/assets/140200815/078af060-bd4a-4a74-b9b3-bb4ca13fc93d)

**Comment by trumank** [comment]
Looks like it can't find some file but the default error message doesn't include the file path. I've made an update to log the file path as well as print a backtrace. If you download the [v0.2.4 release](https://github.com/trumank/drg-mod-integration/releases/tag/v0.2.4) and replace the existing drg_mod_integration binary with the new one, it will give some more context for debugging.

**Comment by yomanoel** [comment]
![image](https://github.com/trumank/drg-mod-integration/assets/140200815/2ef23e17-e8ee-43cc-82df-e5a607e9dc2a)
Here it is

**Comment by trumank** [comment]
Ah, appears it's still trying to use the pak name for the Steam version. That's a bit puzzling since I've heard reports of it working for the Xbox version fine. Regardless, I've released a new version with a fix.

**Comment by yomanoel** [comment]
It worked!! Thank you so much
