### ISSUE TITLE
Nothing shows up ingame (like if game werent modded) + disables mod.io

### ISSUE THREAD

**Issue by figQc** [trumank/drg-mod-integration#88]

**Comment by trumank** [comment]
What mods do you have installed that don't function? If you don't have any mods then the only difference you will see is the modding subsystem is disabled when you click on the modding tab.

**Comment by figQc** [comment]
> What mods do you have installed that don't function? If you don't have any mods then the only difference you will see is the modding subsystem is disabled when you click on the modding tab.

I have ModHub but it doesnt appear, if theres a console well i dont see it

**Comment by Buckminsterfullerene02** [comment]
In the top right corner there's a button to copy your mods to your clipboard, can you send that list please?
![image](https://github.com/trumank/drg-mod-integration/assets/84156063/fd24448e-3d83-4700-9d28-e9e54530d743)

**Comment by figQc** [comment]
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/personal-mini-mollys#2690013
https://mod.io/g/drg/m/more-players-balanced#2515857
https://mod.io/g/drg/m/sgg-framework-files#3096846
https://mod.io/g/drg/m/spawn-menu#1157000

**Comment by figQc** [comment]
> What mods do you have installed that don't function? If you don't have any mods then the only difference you will see is the modding subsystem is disabled when you click on the modding tab.

Everything doesnt works

**Comment by figQc** [comment]
![wrong or no](https://github.com/trumank/drg-mod-integration/assets/143564778/5c9d3fda-0628-499e-9e52-2c7fceffada6)

did i do something wrong in the files?

**Comment by trumank** [comment]
> did i do something wrong in the files?

The only thing you need is `drg_mod_integration.exe` which you get from the releases pages. The other files aren't hurting anything just sitting there but they're unnecessary.

Have you used mods through the official system and do you know what you're looking for to see if they're working? The most obvious mod that comes to mind is [Closer Promotion Terminla](https://mod.io/g/drg/m/closer-promotion-terminal-updated). It just adds a promotion terminal behind you in the spawn pod.

1. Paste the mod URL into the integrator
2. Click install
3. Launch the game
4. Check behind you once the space rig loads

If the promotion terminal isn't there then something is definitely not working. If that's the case, then navigate to the `<steam install dir>/Deep Rock Galactic/FSD/Content/Paks/` directory and show the files there. There should be `FSD-WindowsNoEditor.pak` which contains the game's assets and `mods_P.pak` which contains the mod files. Please upload `mods_P.pak` here so I can inspect it.

**Comment by figQc** [comment]
Yeah I’m good now, I finally found how to use it, I just wasn’t using it properly 

Envoyé de mon iPhone
