### ISSUE TITLE
Clipboard issue on Linux

### ISSUE THREAD

**Issue by Stargazer3240** [trumank/drg-mod-integration#93]
I can't paste my API key into the program because its clipboard is separated from the system's clipboard. I'm using Fedora Linux with GNOME and X11.

**Comment by trumank** [comment]
I also use Linux with i3wm and X11 and the clipboard works fine for me. I don't believe we do anything special with clipboard handling so I would look towards [winit](https://github.com/rust-windowing/winit) if you want to do some digging.

**Comment by trumank** [comment]
Oh, looks like clipboard handling is not (yet) handled in winit, but in egui_wini: https://github.com/emilk/egui/blob/master/crates/egui-winit/src/clipboard.rs

**Comment by Stargazer3240** [comment]
The clipboard didn't work using the software via `cargo run` but, after using `cargo install`, the clipboard is fully functional.
