### ISSUE TITLE
I want to publicize this software on bilibili is it okay?

### ISSUE THREAD

**Issue by nihaopaidaxing** [trumank/drg-mod-integration#97]
I'm very sorry, because my English is very weak, these are all translated by me with a translation software, please forgive me if there is any inappropriate use of words!
I would like to post a video on bilibili recommending it and teaching people how to use it, hopefully it will be approved.
Lastly, I'm very sorry if there are any improper words or grammatical errors, my English ability is really very poor, so please bear with me and thank you very much!

**Comment by nihaopaidaxing** [comment]
I'll include a link to this site in the blurb below the video!

**Comment by trumank** [comment]
Yes, that is fine. Post a link to the video here when you're done? :)

**Comment by nihaopaidaxing** [comment]
Thank you very much for your permission.
With no experience in making videos, there may be many shortcomings, this is the best I can do!

**Comment by nihaopaidaxing** [comment]
Video Link:https://www.bilibili.com/video/BV1TH4y1o7me/?spm_id_from=333.999.0.0&vd_source=a58eb5f7fbbb0b456d24f7aade253031
