### ISSUE TITLE
Install mods failed with "Connection Failed: Connect error:(os error 10060)"

### ISSUE THREAD

**Issue by Tomas-Zhu** [trumank/drg-mod-integration#98]
System:Windows 11 Professional 21H2(22000.2416)
Log:
ERROR drg_mod_integration::gui::message: ureq error: https://cdn.discordapp.com/attachments/817251677086285848/992648087371792404/oo2core_9_win64.dll: Connection Failed: Connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: BaseThreadInitThunk
  12: RtlUserThreadStart

**Comment by Tomas-Zhu** [comment]
I've used a global vpn but that didn't solve the problem either

**Comment by trumank** [comment]
That DLL is required for paks compressed with Oodle (there are only a handful of them I've run into for DRG). Can you download it manually and place it next to the integrator exe? That way the integrator won't have to fetch it itself.

There are some alternative ways to find the DLL if you search:
MD5: `f2db01967705b62aecef3cd3e5a28e4d`
SHA1: `4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624`

**Comment by Tomas-Zhu** [comment]
> That DLL is required for paks compressed with Oodle (there are only a handful of them I've run into for DRG). Can you download it manually and place it next to the integrator exe? That way the integrator won't have to fetch it itself.
> 
> There are some alternative ways to find the DLL if you search: MD5: `f2db01967705b62aecef3cd3e5a28e4d` SHA1: `4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624`

ok,I download it by manual and place it next to drg_mod_integration.exe successfully,finally fixed,thk~

**Comment by skit1791** [comment]
> That DLL is required for paks compressed with Oodle (there are only a handful of them I've run into for DRG). Can you download it manually and place it next to the integrator exe? That way the integrator won't have to fetch it itself.
> 
> There are some alternative ways to find the DLL if you search: MD5: `f2db01967705b62aecef3cd3e5a28e4d` SHA1: `4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624` SHA256: `19452ae1abae65e1305d3818354d4fae7b1200294322f0d9c6d5ddeb7bd9f978` Download and place next to the exe with name `oo2core_9_win64.dll` and it will get loaded


I opened the link, saved it to get a 'oo2core_9_win64' file and then placed it next to **drg_mod_integration.exe**, but I get this:


**ERROR drg_mod_integration::gui::message: oodle hash mismatch expected: 4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624 got: ffc88125007c23ff6711147a12f9bba9c3d197ed
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: BaseThreadInitThunk
  12: RtlUserThreadStart**
  
  
 I wasn't sure what you meant by the alternative ways to find the DLL, not too informed I'm afraid.
